
services:
  app:
    build: .
    container_name: sentencas_app
    env_file:
      - .env 
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"